### ISSUE TITLE
Implement citation tracker

### ISSUE THREAD

**Issue by asuozzo** [asuozzo/eldercare-db#2]
- [ ] Create citation model
- [ ] Write data importer script
- [ ] List on feature page
- [ ] Method for quantifying citation severity [maybe using this](https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/CertificationandComplianc/downloads/usersguide.pdf)
